/*
 * Stoatworks Labs - About window data for Residual.
 *
 * PROVISIONAL, and hand-written. Across the fleet this file is GENERATED by
 * stoatworks-backend/scripts/sync-about.py from the website's projects.json,
 * which is the one place the facts are written down. Residual is not
 * registered there yet, so this is a hand copy adapted from a sibling -- the
 * same thing graticule and photofinish did. Register the project and re-run
 * the sync before release; the next sync overwrites this file, which is the
 * point.
 *
 * `guide` is deliberately EMPTY. There is no user guide, and
 * StoatworksAboutLinks.h leaves a missing link out of the button list rather
 * than shipping a button that opens a 404.
 *
 * `page` and `repo` point at addresses that do not exist yet either, but they
 * are the addresses this project will have, and a 404 from a link somebody
 * chose to press is a different failure from a button that should not be
 * there at all.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "Residual";
    inline constexpr auto slug = "residual";
    inline constexpr auto hook = "Datamosh built as a real codec, for Resolume";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "";
    inline constexpr auto page = "https://stoatworks-labs.com/software/residual/";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/residual";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
